BethanysPieShop/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BethanysPieShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BethanysPieShop.Controllers
{
    [Authorize]
    public class FeedbackController : Controller
    {
                private readonly IFeedbackRepository _feedbackRepository; // this controller will have a dependency on the FeedbackRepository
        //we inject the feedbackRepository  dependency via constructor injection into this controller;
        public FeedbackController(IFeedbackRepository feedbackRepository)
        {
            _feedbackRepository = feedbackRepository;
        }
        // GET: /<controller>/ --> [HttpGet] attribute is the default, so no needs to specify it
        public IActionResult Index()
        {
            return View();
        }

        // POST: /<controller>
        // I need to specify that this method is going to ba called when a post is being received by using an HttpPost attribute
        [HttpPost]
        public IActionResult Index(Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                _feedbackRepository.AddFeedback(feedback); //pass this feedback into the feedbackRepository
                return RedirectToAction("FeedbackComplete"); // I redirect the user to another action method - FeedbackComplete - that I have to create
            }
            return View(feedback); //redirect the user to the same page and pass the same data; user is going to see the page with a validation error (implemented in the view folder in order to be displayed)
        }

        public IActionResult FeedbackComplete()
        {
            return View();
        }


    }
}

BethanysPieShop/Controllers/LogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BethanysPieShop.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BethanysPieShop.Controllers
{
    public class LogoutController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        // Here I need an instance of these methods and I am going to use the dependency injection

        public LogoutController(SignInManager<IdentityUser> signInManager, 
            UserManager<IdentityUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

    }
}

BethanysPieShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>

@inject SignInManager<IdentityUser> signInManager
@inject UserManager<IdentityUser> UserManager
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/content/site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <!--HTML5 NEF element that contains an ul for all the links in the navigation bar-->
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index" class="navbar-brand">Bethany's Pie Shop</a></li>
                    <li><a asp-controller="Feedback" asp-action="Index">Feedback</a></li>
                    <!--by using the below tags the account is created but I cannot see in the main page if I am actually logged in as a user-->
                    <!--<li><a asp-controller="Account" asp-action="Register">Register</a></li>
                    <li><a      asp-controller="Account" asp-action="Login">Log in</a></li>-->
                    <!--I need to access to the SignInManager directly from here. In ASP.Net Core MVC do dependency injection directly in the Razor code  -->
                </ul>

                @if (signInManager.IsSignedIn(User))
                {
                    <form asp-area="" asp-controller="Logout" asp-action="Logout" id="logoutForm"
                          method="post" class="navbar-right">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                        </ul>
                    </form>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li><a id="registerLink" asp-controller="Register" asp-action="Index">Register</a></li>
                        <li><a id="loginLink" asp-controller="Login" asp-action="Index">Log in</a></li>
                    </ul>
                }

            </div>
        </div>
    </nav>
    <div class="container body-content">
        <!--This is going to enable Bootstrap using the class container -->
        <div class=" row">
            <!--all the item will be in arow-->
            @RenderBody()
        </div>
    </div>
</body>
</html>