Controllers/AccountLoginController.cs
using BethanysPieShop.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BethanysPieShop.Controllers
{
    public class AccountLoginController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;

        public AccountLoginController(SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        // GET: /<controller>/
        //my AccountController will need to able to log in, so I replace the Index Method with Login;
        public IActionResult Login()
        {
            return View();
        }

        //I need to capture that data (in my Login.cshtml) in my AccountController.
        //I need to create a second Action method when a Post request is sent to the Controller

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(loginViewModel);
            }

            var user = await _userManager.FindByNameAsync(loginViewModel.LoginUserName);

            if (user != null)
            {
                var result = await _signInManager.PasswordSignInAsync(user, loginViewModel.LoginPassword, false, false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            ModelState.AddModelError("", "User name/password not found");
            return View(loginViewModel);
        }
    }
}
    



Controllers/AccountLogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BethanysPieShop.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BethanysPieShop.Controllers
{
    public class AccountLogoutController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        // Here I need an instance of these methods and I am going to use the dependency injection

        public AccountLogoutController(SignInManager<IdentityUser> signInManager, 
            UserManager<IdentityUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

    }
}

Controllers/AccountRegisterController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using BethanysPieShop.ViewModels;

namespace BethanysPieShop.Controllers
{
    public class AccountRegisterController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;

        public AccountRegisterController(SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public IActionResult Register()
        {
            return View(new RegisterViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel registerViewModel)
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser() { UserName = registerViewModel.RegisterUserName };
                var result = await _userManager.CreateAsync(user, registerViewModel.RegisterPassword);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View(registerViewModel);
        }

    }
}


Views/AccountLogin/Login.cshtml
<!--in this view I want to capture the info entered by the users do the login info (username and psw). -->
<!--I don't have a domain class that can be used for this so we have to create a login view model -->
@model LoginViewModel

<h2>Before contacting us, please log in or <a asp-action="Register" asp-controller="Account">register!</a></h2>

<form asp-action="Login" asp-controller="AccountLogin" method="post" class="form-horizontal" role="form">

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="LoginUserName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="LoginUserName" class="form-control" />
            <span asp-validation-for="LoginUserName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="LoginPassword" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="LoginPassword" class="form-control" />
            <span asp-validation-for="LoginPassword" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Log in" />
        </div>
    </div>
</form>